package com.example.olx.utilities

object Constants {

    val CREATED_DATE = "created_date"
    val CITY_NAME = "city_name"
    val USER_PHOTO = "user_photo"
    val USER_NAME = "user_name"
    val USER_ID = "user_id"
    val USER_EMAIL = "user_email"
    val SharedPrefName = "OLX"
    val USER_ADDRESS = "user_address"
    val USER_PHONE = "user_phone"
    val BRAND = "brand"
    val YEAR = "year"
    val AD_TITLE = "adTitle"
    val AD_DESCRIPTION = "description"
    val KM_DRIVEN = "kmDriven"
    val TYPE = "type"
    val PRICE = "price"
    val PHONE = "phone"
    val ADDRESS = "address"
    val CURRENCY_SYMBOL = "Rs. "
    val IMAGE_PATHS = "image_paths"
    val KEY = "key"
    val DOCUMENT_ID = "doc_id"
    val CATEGORIES = "Categories"
    val ID = "id"
    val CAR = "Car"
}